### ISSUE TITLE
【找个地方回复】

### ISSUE THREAD

**Issue by vikiboss** [TwelveGJ/qq_bot#1]
谢谢对 60s 的打赏～

然后看你也对机器人相关开发很感兴趣，正好我也是最近在做这方面的开发，如果可以，一起玩呀～

> 等回复完就关闭，不占用位置啦。

**Comment by TwelveGJ** [comment]
好嘞！刚接触做这个，学习学习~~

**Comment by vikiboss** [comment]
企鹅 UID VikiQAQ

**Comment by TwelveGJ** [comment]
github同名，直接搜twelvegj就OK
